name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 14
        id: setup-java-14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64

      - name: Build
        id: build
        run: ./gradlew release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './build/distributions/*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
